### ISSUE TITLE
Missing HTTP Signature RFC

### ISSUE THREAD

**Issue by buger** [mnot/rfc.fyi#21]
Hi! 

I just checked a few RFCs, most of them were found, but this one for example missing:
https://datatracker.ietf.org/doc/html/draft-cavage-http-signatures-12

Cheers.

**Comment by mnot** [comment]
Hi!

That document isn't an RFC; it's an _Internet-Draft_, which is a document that *might* become an RFC. Also that particular one has been replaced by [this one](https://httpwg.org/http-extensions/draft-ietf-httpbis-message-signatures.html).

I've looked at including I-Ds, but the problem is the size of the corpus; rfc.fyi loads all of the metadata into the browser when you load the page, and while this works for RFCs, there are many, many more Internet-Drafts.

**Comment by buger** [comment]
Makes sense!
